#pragma once

#define LV_ATTRIBUTE_TICK_INC IRAM_ATTR
#define LV_ATTRIBUTE_TIMER_HANDLER IRAM_ATTR
#define LV_ATTRIBUTE_FLUSH_READY IRAM_ATTR
#define LV_ATTRIBUTE_FAST_MEM IRAM_ATTR

#define LV_CONF_SKIP
#define LV_CONF_INCLUDE_SIMPLE
#define LV_LVGL_H_INCLUDE_SIMPLE
#define LV_USE_THEME_DEFAULT 1
#define CONFIG_LV_USE_FONT_SUBPX 1
#define LV_COLOR_DEPTH 16
#define LV_FONT_MONTSERRAT_30 1
#define USER_SETUP_LOADED 1
#define LV_USE_LARGE_COORD 1

#define LV_DISP_DEF_REFR_PERIOD 15
#define LV_INDEV_DEF_READ_PERIOD 30 
